name: Force Instant Google Crawl
on:
  push:
    branches:
      - main
jobs:
  google-index:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Current Code
        uses: actions/checkout@v4

      - name: Trigger Core Indexing API
        uses: robingenz/action-google-indexing@v1.0.0
        with:
          siteUrl: 'https://www.apcmaid.com/computer-repair-rochester-mn/'
          gcpServiceAccountKey: $${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
